/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b98211911d5569ad7a36fee6972d875f)
interface __BaseEnv_Env {
	PHOTOS: R2Bucket;
	BACKUPS: R2Bucket;
	DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	ADMIN_PASSWORD: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_PASSWORD">> {}
}
